
spring:
  application:
    name: sb-msvc-product-api
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

config:
  url: http://localhost:8080/api/driver/properties
  scope: sb-product-api
  key: 0ce521fb-77f9-459b-b215-ba234dddd90a

server:
  port: 8082